In [2]:
# Randomly shuffles elements of an array in-place (original array changes).

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 4 3 1 2]


In [3]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [14, 51, 16],
                 ])

np.random.shuffle(arr2) # Rows shuffle, columns stay intact
print(arr2)


[[ 4  5  6]
 [ 1  2  3]
 [14 51 16]]


In [6]:
# Returns unique elements from an array (sorted by default).
# arr = np.array([1, 2, 2, 3, 4, 4, 5])
# print(np.unique(arr))


unique, counts = np.unique(arr, return_counts=True)
print(unique)
print(counts)


[1 2 3 4 5]
[1 2 1 2 1]


In [8]:
# Changes the shape and size of an array
# If size increases → elements repeat

arr = np.array([1, 2, 3, 4])
print(np.resize(arr, (3, 3)))


[[1 2 3]
 [4 1 2]
 [3 4 1]]


In [10]:
# Converts a multi-dimensional array into 1D

arr2 = np.array([[1, 2],
                 [3, 4]])

flat = arr2.flatten()
flat[0] = 100

print(arr2)
print(flat)


[[1 2]
 [3 4]]
[100   2   3   4]


In [12]:
# Also converts array into 1D, but returns a view if possible

rav = arr2.ravel()
rav[0] = 200

print(arr2)
print(rav)


[[200   2]
 [  3   4]]
[200   2   3   4]


In [14]:
# Insert in 1D Array

import numpy as np

arr = np.array([10, 20, 30, 40])
# new_arr = np.insert(arr, 2, 99)
# print(new_arr)

# Insert multiple values

arr1=np.insert(arr, 1, [5, 6])
print(arr1)


[10  5  6 20 30 40]


In [ ]:
# Insert in 2D Array (Row-wise)

arr2 = np.array([[1, 2],
                 [3, 4]
                ])

row = [9, 9]

print(np.insert(arr2, 1, row, axis=0))


[[1 9 2]
 [3 9 4]]


In [17]:
# Insert in 2D Array (Column-wise)

col = [8, 8]
print(np.insert(arr2, 1, col, axis=1))


[[1 8 2]
 [3 8 4]]


In [ ]:
# Delete in NumPy Array
arr = np.array([10, 20, 30, 40])

# new_arr = np.delete(arr, 1)

# new_arr1 = np.delete(new_arr, 1)

# print(new_arr1)
# print(new_arr)

# Delete multiple elements

# newarr=np.delete(arr, [0, 2])
# print(newarr)

# Delete row from 2D Array
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

# Delete Row from 2D Array
# print(np.delete(arr2, 1, axis=0))

# Delete column from 2D Array
print(np.delete(arr2, 0, axis=1))

[[2]
 [4]
 [6]]
