In [17]:
import numpy as np

d1=np.array([3,5,7,2])

print("Data type: ",d1.dtype)
d1

Data type:  int64


array([3, 5, 7, 2])

In [20]:
import numpy as np

# d1=np.array(["A","B"])
# d1=np.array([1,2,"A","B"])
d1=np.array([1,2,"A","B",5.6,8.67])

print("Data type: ",d1.dtype)
d1


Data type:  <U32


array(['1', '2', 'A', 'B', '5.6', '8.67'], dtype='<U32')

In [25]:
d1=np.array([5.6,8.67],dtype=np.int8)
# d1=np.array([5.6,8.67],dtype="i")

print("Data type: ",d1.dtype)
d1


Data type:  int8


array([5, 8], dtype=int8)

In [26]:

d1=np.array([5.6,8.67])
# new = np.int16(d1)
new = np.int16(d1)

print("Data type: ",new.dtype)
new

Data type:  int16


array([5, 8], dtype=int16)

In [6]:

d1=np.array([5,8])
new = d1.astype(float)

print("Data type: ",new.dtype)
new

Data type:  float64


array([5., 8.])

In [27]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([3,6,2,7])

varAdd1=var1+var2
varSub2=var1-var2
varMul3=var1*var2
varDiv4=var1/var2

print("Addition is : ",varAdd1)
print("Subtraction is : ",varSub2)
print("Multilication is : ",varMul3)
print("Divide is : ",varDiv4)

Addition is :  [ 4  8  5 11]
Subtraction is :  [-2 -4  1 -3]
Multilication is :  [ 3 12  6 28]
Divide is :  [0.33333333 0.33333333 1.5        0.57142857]


In [ ]:
import numpy as np
var1=np.array([1,2,3,4])

print("Vector plus: ",var1+2)
print("Vector minus: ",var1-1)
print("Vector multiply: ",var1*3)
print("Vector divide: ",var1/2)
print("Vector floor divide: ",var1//2)  # 7//3=2.33=2  9//4=2
print("Vector Modulous: ",var1%3) #
print("Vector Modulous: ",var1**2)

MAn plus:  [3 4 5 6]
Vector minus:  [0 1 2 3]
Vector multiply:  [ 3  6  9 12]
Vector divide:  [0.5 1.  1.5 2. ]
Vector floor divide:  [0 1 1 2]
Vector Modulous:  [1 2 0 1]
Vector Modulous:  [ 1  4  9 16]


In [31]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])

newVal=np.add(var1,var2)
print(newVal)
# newVal=np.add(var1,3)

newVal=np.multiply(var1,3)
print(newVal)

newVal=np.mod(var1,3)
print(newVal)
# newVal

[2 4 6 8]
[ 3  6  9 12]
[1 2 0 1]


In [40]:
# arrMin=np.array([4,6,8,45])
# print(np.min(arrMin))  # element
# print("Index",np.argmin(arrMin)) # index value

# arrMax=np.array([4,6,8,45])
# print(np.max(arrMax))
# print("Index",np.argmax(arrMax))


# var1=np.array([[4,5,7],[1,2,9]])
# print(var1)
# print(np.min(var1,axis=0))
# print(np.min(var1,axis=1))


# arrSqrt=np.array([4,25,8,45])
# print(np.sqrt(arrSqrt))

# arrSin = np.array([45, 60, 90])
# result = np.sin(arrSin * np.pi / 180)
# print(result)


arrCumSum=np.array([4,6,8,4])
print(np.cumsum(arrCumSum))

[ 4 10 18 22]


In [41]:
arr1=np.array([[1,3,8],[4,7,4]])
print(arr1)
print(arr1.shape)

[[1 3 8]
 [4 7 4]]
(2, 3)


In [ ]:
arr1=np.array([1,3,8,8,4],ndmin=3)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[1 3 8 8 4]]
2
(1, 5)


In [44]:
arr1=np.array([1,3,8,8,4,0])
print(arr1)
print(arr1.ndim)

newDim=arr1.reshape(2,3)
print(newDim)
print(newDim.ndim)

newDim1=newDim.reshape(-1)
print(newDim1)
print(newDim1.ndim)

[1 3 8 8 4 0]
1
[[1 3 8]
 [8 4 0]]
2
[1 3 8 8 4 0]
1


In [45]:
a = np.array([1, 2, 3])    # shape (1,3)

b = np.array([[10],        # shape (3,1)
              [20],
              [30]])   

print(a + b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [46]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])    # shape (2, 3)

b = np.array([10, 20, 30])   # shape (1,3)

print(a + b)


[[11 22 33]
 [14 25 36]]


In [47]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10],
              [20]])

print(a + b)


[[11 12 13]
 [24 25 26]]
