In [27]:
import numpy as np
arr1=np.array([1,4,7,3,8])
print("My array is: ",arr1)

myList=[3,8,5,3]
print("MyList is: ",myList)

# print(arr1[2])

My array is:  [1 4 7 3 8]
MyList is:  [3, 8, 5, 3]


In [28]:
%timeit [i*2 for i in range(1,21)]

518 ns ± 23.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [29]:
%timeit np.arange(1,21)*2

2 μs ± 131 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [30]:
import numpy as np

arr=np.array([3,5,7,9])

# print(arr)
print(type(arr))
print(arr.ndim)
# arr


<class 'numpy.ndarray'>
1


In [31]:

arr2=np.array([[3,6,7],
               [2,7,3],
               [4,2,9]
               ])
# arr2=np.array([[3,5,7,9],[5,3,7,2],[2,5,8,2]])
# # arr2=np.array([[4,4,6],[3,8,9]])

arr2=np.array([[[3,8,3],[4,5,6],[7,9,1]],
               [[3,6,7],[2,7,3],[4,2,9]]])

# arr2
# print(arr2[1][0])
# print(arr2[1][1][1])
# print(arr2.ndim)

In [32]:
arr3=np.array([[[5,3,7,2],[2,5,8,2],[4,5,7,2]]])

# arr2
print(arr3)
print(arr3.ndim)

[[[5 3 7 2]
  [2 5 8 2]
  [4 5 7 2]]]
3


In [33]:
arrN=np.array([1,3,5,6,5],ndmin=10)

# arr2
print(arrN)
print(arrN.ndim)

[[[[[[[[[[1 3 5 6 5]]]]]]]]]]
10


In [34]:
import numpy as np

zerosArr1=np.zeros(5)
zerosArr2=np.zeros((4,6))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[0. 0. 0. 0. 0.]
--------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [35]:
zerosArr1=np.ones(4)
zerosArr2=np.ones((2,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[1. 1. 1. 1.]
--------------
[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
# arrEmp=np.empty((2,3)) # Random garbage values

# print(arrEmp)

# arrRange=np.arange(25)
# print(arrRange)
# arrRange=np.arange(15)*2
# arrRange

In [37]:
arrDiogonal=np.eye(4)
print(arrDiogonal)

arrDiogonal=np.eye(3,4)
arrDiogonal

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [38]:
arr_lin=np.linspace(5,20,num=5)
arr_lin

array([ 5.  ,  8.75, 12.5 , 16.25, 20.  ])

In [ ]:
# var1=np.random.rand(15)
# var2=np.random.rand(3,3)
# var3=np.random.randn(5)
var4=np.random.randn(3,4)

# print("Random 1d Array Between 0 to 1:",var1)
# print("Random 2d Array Between 0 to 1:",var2)
# print("Random 1d Array Between closed to zero Negative Positive:",var3)
print("Random 2d Array Between closed to zero Negative Positive:",var4)

# arr1=np.sum(var4)
# print(arr1/9)


Random 2d Array Between closed to zero Negative Positive: [[ 1.43457213  2.14563079 -1.68550841 -1.22899001]
 [ 0.77709022 -0.61739326 -1.65365926  1.07449963]
 [ 1.2089498  -1.14138468 -0.39560681  0.56232891]]
0.05339211742512308


In [48]:
var5=np.random.ranf(5)
var6=np.random.ranf((4,5))
var7=np.random.randint(40,100,5)


print("Random 1d Array Between [0,1):",var5)
print("Random 2d Array Between [0,1):",var6)
print("Random integer 1d Array Between 4 to 10:",var7)

Random 1d Array Between [0,1): [0.33899907 0.41083929 0.64287633 0.6726456  0.64707688]
Random 2d Array Between [0,1): [[0.39523792 0.87088481 0.84305361 0.38751573 0.05033076]
 [0.38447525 0.3851948  0.87776233 0.01885796 0.51796471]
 [0.0381224  0.64955658 0.70152917 0.21121828 0.65949501]
 [0.89071933 0.14132244 0.30981373 0.68360995 0.02098299]]
Random integer 1d Array Between 4 to 10: [46 52 78 53 68]
