In [ ]:
import numpy as np
arr1=np.array([1,4,7,3,8])
print("My array is: ",arr1)

myList=[3,8,5,3]
print("MyList is: ",myList)

My array is:  [1 4 7 3 8]
MyList is:  [3, 8, 5, 3]


In [ ]:
%timeit [i*2 for i in range(1,21)]

519 ns ± 18.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
%timeit np.arange(1,21)*2

2.88 μs ± 607 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
import numpy as np

arr=np.array([3,5,7,9])

# print(arr)
print(type(arr))
print(arr.ndim)
# arr



<class 'numpy.ndarray'>
1


In [ ]:
arr2=np.array([[3,5,7,9],[5,3,7,2],[2,5,8,2]])
# # arr2=np.array([[4,4,6],[3,8,9]])
# arr2=np.array([[[3,8,3],[4,5,6],[7,9,1]]])

# arr2
print(arr2)
print(arr2.ndim)

[[3 5 7 9]
 [5 3 7 2]
 [2 5 8 2]]
2


In [ ]:
arr3=np.array([[[5,3,7,2],[2,5,8,2],[4,5,7,2]]])

# arr2
print(arr3)
print(arr3.ndim)

[[[5 3 7 2]
  [2 5 8 2]
  [4 5 7 2]]]
3


In [ ]:
arrN=np.array([1,3,5,6,5],ndmin=10)

# arr2
print(arrN)
print(arrN.ndim)

[[[[[[[[[[1 3 5 6 5]]]]]]]]]]
10


In [ ]:
import numpy as np

zerosArr1=np.zeros(4)
zerosArr2=np.zeros((4,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[0. 0. 0. 0.]
--------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
zerosArr1=np.ones(4)
zerosArr2=np.ones((7,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[1. 1. 1. 1.]
--------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# arrEmp=np.empty((2,3)) # Random garbage values

# print(arrEmp)

# arrRange=np.arange(15)
# print(arrRange)
arrRange=np.arange(5)*2
arrRange

array([0, 2, 4, 6, 8])

In [ ]:
# arrDiogonal=np.eye(4)
# print(arrDiogonal)

arrDiogonal=np.eye(3,4)
arrDiogonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
arr_lin=np.linspace(0,20,num=5)
arr_lin

array([ 0.,  5., 10., 15., 20.])

In [ ]:
# var1=np.random.rand(5)
# var2=np.random.rand(3,3)
# var3=np.random.randn(5)
# var4=np.random.randn(3,4)

# print("Random 1d Array Between 0 to 1:",var1)
# print("Random 2d Array Between 0 to 1:",var2)
# print("Random 1d Array Between closed to zero Negative Positive:",var3)
# print("Random 2d Array Between closed to zero Negative Positive:",var4)

In [ ]:
# var5=np.random.ranf(5)
# var6=np.random.ranf((4,5))
# var7=np.random.randint(4,67,5)

# print("Random 1d Array Between [0,1):",var5)
# print("Random 2d Array Between [0,1):",var6)
# print("Random integer 1d Array Between 4 to 10:",var7)