In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # first element
print(arr[2])   # third element
print(arr[-1])  # last element


10
30
50


array([10, 20, 30, 40, 50])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# print(arr[1:4])
# print(arr[:3])
# print(arr[:])
# print(arr[::2])


[10 30 50]


In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# print(arr2[0][1])   # row 0, column 1
# print(arr2[0, 1])   # row 2, column 2

# print(arr2[1:3])  # Row Slicing
# print(arr2[:, 1]) # Column Slicing
# print(arr2[2, 1:3]) # Row + Column slicing
# print(arr2[1:, :2]) # Row + Column slicing


[[5 6]
 [8 9]]


In [39]:
import numpy as np

arr = np.array([10, 20, 30, 40])

for i in arr:
    print(i+8)


18
28
38
48


In [41]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

for row in arr2:
    print(row)

for row in arr2:
    for elem in row:
        print(elem)



[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
# for row in arr2:
#     for element in row:
#         print(element)


1
2
3
4
5
6


In [46]:
# arr2 = np.array([[[1, 2, 3],[4,6,7,]]])
# for x in np.nditer(arr2):
#     print(x)

arr3 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# for x in np.nditer(arr3):
#     print(x)

for index, value in np.ndenumerate(arr3):
    # print(index, value)
    print(f"The index is: {index} and value is: {value}")

The index is: (0, 0) and value is: 1
The index is: (0, 1) and value is: 2
The index is: (0, 2) and value is: 3
The index is: (1, 0) and value is: 4
The index is: (1, 1) and value is: 5
The index is: (1, 2) and value is: 6


In [47]:
arr = np.array([10, 20, 30, 40])
for x in np.nditer(arr, flags=['buffered'],op_dtypes="S"):
    print(x)

print(arr)


np.bytes_(b'10')
np.bytes_(b'20')
np.bytes_(b'30')
np.bytes_(b'40')
[10 20 30 40]


In [51]:
import numpy as np

arr = np.array([10, 20, 30, 40])

v = arr.view()
# v = arr
v[1] = 200

print("Original:", arr)
print("View:", v)



Original: [ 10 200  30  40]
View: [ 10 200  30  40]


In [53]:
arr = np.array([10, 20, 30, 40])
c = arr.copy()
c[0] = 999

print("Original:", arr)
print("Copy:", c)


Original: [10 20 30 40]
Copy: [999  20  30  40]


In [55]:
arr = np.array([1,2 , 3, 4, 5])

s = arr[1:4]

s[0] = 100

print(s)
print(arr)


[100   3   4]
[  1 100   3   4   5]


In [56]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6]


In [58]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))


[[1 2 5 6]
 [3 4 7 8]]


In [62]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

# print(np.stack((a, b), axis=1))
# print(np.hstack((a, b)))
np.dstack((a, b))

# np.vstack((a, b))


array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
# Row-wise split
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])

# print(np.array_split(arr2, 2, axis=0))

# Column-wise split
print(np.array_split(arr2, 2, axis=1))



[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [77]:
# 1. Search
import numpy as np

arr = np.array([10, 20, 30, 20, 40])

# print(np.where(arr == 20))
# print(np.where(arr > 25))
print(arr[arr > 25])

# # 2. Sort
arr = np.array([40, 10, 30, 20])

# print(np.sort(arr))  # Ascending order
print(np.sort(arr)[::-1]) # Descending order



[30 40]
[40 30 20 10]


In [80]:
# 2D Array Sort
arr2 = np.array([[13, 2, 11],
                 [6, 5, 4],
                 [9, 2, 14]])

print(np.sort(arr2,axis=1))
# print(np.sort(arr2,axis=0))


[[ 2 11 13]
 [ 4  5  6]
 [ 2  9 14]]


In [87]:
# 3. searchsorted()
# arr = np.array([110, 20, 300, 40,89,34,12])
# arr = np.array([10, 12,20,30,34,40,89])

# print(np.searchsorted(arr, 25))
# print(np.searchsorted(arr, 40, side='left'))

# 4. Filter
# arr = np.array([10, 25, 30, 15, 40])

# print(arr[arr > 20]) # Method 1: Boolean condition
# print(arr[arr > 20]) # Method 2: Boolean array

marks = np.array([45, 67, 89, 32, 76])

# Pass students
# print(marks[marks >= 40])

# # Topper position
print(np.searchsorted(np.sort(marks), 80))


4
