In [ ]:
Day 2 
✅ NumPy Basics
✅ Pandas Series & DataFrame
✅ Importing CSV/Excel files
✅ Data inspection (head, tail, info, describe)
✅ Filtering, Sorting
✅ Adding, Updating, Deleting Columns
✅ Handling Missing Values
✅ Hands-on dataset practice

In [ ]:
What is NumPy?

NumPy = Numerical Python
Used for:
✅ Fast mathematical operations
✅ Arrays (better than lists)
✅ Scientific computing
✅ Basis for Pandas, ML algorithms

In [ ]:
A NumPy array (ndarray) is a multi-dimensional, indexed, fixed-type container for numbers.

Think of it as:

✅ A super-fast version of Python lists, designed for:

Mathematics

Data analytics

Machine learning

Scientific computing

 Why NumPy Arrays are Better than Python Lists?

                                                                             | Feature        | Python List   | NumPy Array              |
| -------------- | ------------- | ------------------------ |
| **Speed**      | Slow          | ⚡ Very fast              |
| **Memory**     | More memory   | Uses less memory         |
| **Operations** | Loop required | Direct vector operations |
| **Data Type**  | Mixed allowed | Single type (faster)     |

                                                                             

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
Types of NumPy Arrays

1D Array – like a list
[10, 20, 30]

2D Array – like an Excel table
[[1, 2, 3],
 [4, 5, 6]]

In [2]:
arr = np.array([10, 20, 30])

print(arr + 5)   # Broadcasting
print(arr * 2)
print(arr / 10)

[15 25 35]
[20 40 60]
[1. 2. 3.]


In [3]:
#1.5 Mathematical Functions
arr = np.array([10, 20, 30, 40])

print(arr.max())
print(arr.min())
print(arr.mean())
print(np.sum(arr))

40
10
25.0
100


In [ ]:
Hands-on Exercise 

List of sales = [12000, 15000, 18000, 22000]
Calculate:

✅ Total
✅ Average
✅ Max sale

Using NumPy.

In [ ]:
Introduction to Pandas 

Pandas is the MOST important library for Data Analytics.